const assert=require('node:assert/strict'),C=require('./calculadora-promociones');
const base={tipo:'descuento',precio_habitual:22000,precio_oferta:17500,costo_base:7000,costo_trabajo:1000,empaque:500,costo_extra:0,valor_extra:0,comision:2500,minimo:3000,canjes:30};
let n=0;function check(nombre,fn){fn();n++;console.log('[PASS] '+nombre);}
check('Importes en centavos: campo vacío, negativo o más de dos decimales no pasa',()=>{assert.equal(C.centavos('12.10','Precio'),1210);assert.equal(C.centavos('0','Costo'),0);for(const v of ['',null,'-1','1.001','Infinity','1e2'])assert.throws(()=>C.centavos(v,'Costo'));});
check('Mismo desayuno: ahorro $45 y contribución $65 después de todos los costos variables',()=>{const r=C.calcular(base);assert.equal(r.ahorro,4500);assert.equal(r.contribucion,6500);assert.throws(()=>C.calcular({...base,precio_oferta:11000}));});
check('Complemento: valor para el cliente distinto del costo para el negocio',()=>{const r=C.calcular({...base,tipo:'complemento',precio_oferta:22000,costo_extra:800,valor_extra:4000});assert.equal(r.ahorro,4000);assert.equal(r.contribucion,10200);assert.throws(()=>C.calcular({...base,tipo:'complemento'}));assert.throws(()=>C.calcular({...base,valor_extra:4000}));});
check('Paquete: no duplica valor del complemento ni permite una oferta sin beneficio',()=>{assert.equal(C.calcular({...base,tipo:'paquete'}).ahorro,4500);assert.throws(()=>C.calcular({...base,tipo:'paquete',valor_extra:4000}));assert.throws(()=>C.calcular({...base,precio_oferta:22000}));});
check('Alternativas usan los costos informados y respetan el mínimo',()=>{const opciones=C.alternativas({...base,tipo:'complemento',costo_extra:800,valor_extra:4000});assert.ok(opciones.some(o=>o.numeros.tipo==='complemento'));assert.ok(opciones.every(o=>o.resultado.contribucion>=base.minimo));const paquete=C.alternativas({...base,tipo:'paquete',costo_extra:800});assert.ok(paquete.every(o=>o.numeros.costo_extra===800));const sinDescuento=C.alternativas({...base,tipo:'complemento',minimo:11000,valor_extra:4000});assert.equal(sinDescuento.length,1);assert.equal(sinDescuento[0].numeros.tipo,'complemento');});
check('Ficha deja de corresponder si cambian descripción, tarifa, días o cupos autorizados',()=>{const c={title:'Fonda',desc:'Desayuno $175',tarifa:25,stock:30,dias:[1,2]};const f={version:1,confirmado:true,numeros:base,resultado:C.calcular(base),referencia:'Desayuno de carta',beneficio:'Ahorro de $45',aprobador:'Dueño',publicacion:C.publicacion(c)};C.validar(f,c);for(const x of [{desc:'Otro desayuno'},{tarifa:45},{dias:[3]},{stock:31}])assert.throws(()=>C.validar(f,{...c,...x}));assert.throws(()=>C.validar({...f,confirmado:false},c));C.validar(f,{...c,stock:29});});
console.log('Calculadora: '+n+' pruebas aprobadas.');
